name: Java 11 CI - Maven Package

on:
  release:
    types:
      [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.ARTIFACT_REGISTRY_KEY }}'
      - name: Build and Deploy with Maven
        run: mvn -B clean deploy

